---
title: "Análise de viabilidade e listagem de processos"
format: revealjs
execute:
  echo: false
  warning: false
---


## Análise de viabilidade

Antes de iniciar qualquer pesquisa jurimétrica, é recomendável realizar uma análise de viabilidade do projeto para saber se ele é executável e viável. Fatores a serem considerados.

## Viabilidade teórica

Verifica se o tema escolhido é relevante e possui um embasamento teórico sólido.

Avalia se há literatura científica disponível e acessível para fundamentar o problema de pesquisa.


## Viabilidade prática

A pesquisa é necessária e seus resultados serão efetivamente usados para subsidiar um processo ou a elaboração de uma política pública?

As perguntas da pesquisa são frutos da experiência ou conhecimento teórico bem fundado de quem a encomenda?

## Viabilidade Metodológica:

Avalia se os métodos propostos (quantitativos, qualitativos ou mistos) são adequados e aplicáveis ao objeto de estudo.

Considera se há ferramentas, técnicas ou instrumentos apropriados para a coleta e análise de dados.

Viabilidade Técnica:

Avalia se a pesquisa pode ser realizada com os recursos materiais e tecnológicos disponíveis, como equipamentos, softwares ou laboratórios.

Verifica se há infraestrutura suficiente para a realização do estudo.

## Viabilidade Financeira

Analisa os custos envolvidos, como viagens, aquisição de equipamentos, insumos e publicação dos resultados.

Verifica se há fontes de financiamento ou orçamento disponível para cobrir as despesas.

Viabilidade Temporal

Considera se a pesquisa pode ser concluída dentro do prazo disponível, especialmente em projetos vinculados a cursos acadêmicos, editais ou prazos institucionais.

Avalia a compatibilidade do cronograma com o escopo do projeto e as etapas planejadas.


## Viabilidade Ética e Legal

Verifica se a pesquisa envolve questões sensíveis (como seres humanos ou dados pessoais) e se segue as normas éticas pertinentes, como aprovação em comitês de ética.

Avalia se há autorizações legais necessárias para a condução da pesquisa, como permissões em áreas protegidas.

## Viabilidade Pessoal e Institucional

Analisa se o pesquisador e a equipe possuem as competências necessárias para conduzir a pesquisa.

Verifica se a instituição de apoio (universidade ou centro de pesquisa) oferece suporte suficiente para a execução.

## Viabilidade em jurimetria

1. Os dados que quero coletar existem?

2. Se existem, são coletáveis?

3. Se são coletáveis, qual a sua qualidade?

## Recomendações

1. Evite pedir muito. Se possível, a pesquisa deve responder no máximo três perguntas.

2. 

## Listagem dos processos

1. Fonte: tribunal, casa legislativa etc.

2. TPUs:
  - Assunto
  - Classe processual
  - Movimentação processual
  - Documentos

## Listagem de processos

- Processos distribuídos

- Processos julgados

